### PR TITLE
Added mechanism to depend on Avro schemata and protocols.

### PR DESCRIPTION
**Pull request by silasdavis**
This pull request adds the ability to depend on externally (with respect to a gradle project) defined Avro types, so that you can refer to them by their fully-qualified type name in avro schemata and have the Avro parser embed the type. Artifacts (zips or jars) containing avro files can be specified as dependencies in the same was as Java artifacts using the specially defined `avro` configuration.

This is somewhat in parallel to import statements in avdl. Unfortunately the avro protocol parser is more limited to the Schema parser; lacking the ability to to be passed a map of known types. Also the import statement relies on protocols residing relative to the protocol file being parsed. I describe a workaround for this in my updates to the readme.

The changes I have made are:

- Modified the GenerateAvroJava task to accept a map of types to be passed to the Schema parser (extending the existing accumulation of types that is happening anyway when attempting to parse possibly dependent types local to the project).
- Added in single project-wide GenerateAvroJava task and GenerateAvroProtocol tasks to handle dependencies. The dependency graph for the default tasks now looks like this: [Avro plugin tasks](http://bit.ly/1F6dEr6)
- Removed AvroPluginSpec.groovy (and the spock testing framework dependency); I had issues getting spock to work on my system -- certainly not a reason to remove this test -- but on reading the test I didn't think it added much value at all to the project; the test was rather circular and didn't really test any behaviour, whilst incurring the cost of a slightly more involved testing methodology for a project which in my evaluation didn't benefit from it. I realise I run the risk of being overly opinionated here, so if you disagree I will try and add the test and spock back. I should also say I added tests that provide better coverage that what was there before.
- Updated readme to describe dependency functioning.

### CODE REVIEW

**Comment by silasdavis** [comment]
I had some test failures that seemed to be related to the fact quite an old version of gradle was in use via the wrapper (version 1.12). I upgraded the gradle wrapper to 2.3.

**Comment by davidmc24** [comment]
Thanks for the great pull request!  The plugin change looks good, as does the gradle wrapper upgrade.  What was your thinking behind replacing Spock with JUnit?  Is `deps-in-archive.zip` used somewhere in the plugin/tests, or was it used by you in manual testing?

**Comment by davidmc24** [comment]
Checked back to see if you'd responded to my comment... and found that it looks like you'd already included a rationale in your original description that I somehow completely missed... along with other relevant notes that need further discussion.  No clue how that happened.

I don't think that having a single "avro" configuration and using it for a single cross-source-set "generate" step is the right approach.  Instead, I think that the generation should remain with task-per-source-set, and we should add a configuration per-sourceset, so you can (for example) add an avro dependency for your "test" source generation but not your "main" source generation.

I've upgraded master to Gradle 2.6, so that portion can be removed from this pull request.  I'm not willing to accept moving from Spock to JUnit, but if you aren't able to provide tests in Spock format, I'm willing to do that.

**Comment by davidmc24** [comment]
Closing due to not handling multiple configurations, and no further response from contributor.

**Pull request closed without merging**
