### PR TITLE
Release 0.8.1 for Gradle 5 compatibility

### PR DESCRIPTION
**Pull request by DPUkyle**
Hi David.

I work with several hundred hadoop projects that currently use version 0.8.0, avro 1.7.7 and are built with Gradle 4.

gradle-avro-plugin:0.8.0 was compiled against Gradle 2 and fails at runtime with Gradle 5. As a workaround for #66, I made a version 0.8.1 of the plugin which works with Gradle 5, but keeps avro 1.7.7. There are no other meaningful changes.

I would like you to please release this, and of course I'm happy to help. GitHub says the branch can't be merged (understandably) since this is far behind HEAD.

My suggestion is to:

1. Checkout tag `0.8.0`
2. Create a new branch, perhaps call it `rel/0.8.1`
3. Push the new branch to GitHub
4. Merge this PR into branch `rel/0.8.1`... it should merge cleanly
5. Publish it somewhere

I hope this is reasonable!

Thanks and again I'm happy to help. I'm happy to squash the commits as well if you're happy with the result.

Kyle

### CODE REVIEW

**Comment by davidmc24** [comment]
@DPUkyle Thanks for the contribution.  Reviewing now...

**Comment by davidmc24** [comment]
@DPUkyle Your request is reasonable, and I'm inclined to go forward with it.  I'll give a go at releasing this as 0.8.1.

**Comment by DPUkyle** [comment]
Thanks David! It looks like we're good? 

https://bintray.com/commercehub-oss/main/gradle-avro-plugin/0.8.1#files/com%2Fcommercehub%2Fgradle%2Fplugin%2Fgradle-avro-plugin%2F0.8.1

**Comment by davidmc24** [comment]
@DPUkyle Yep, 0.8.1 has been released to jcenter based on your changes, with a few minor tweaks.  It should meet your needs.  If you have any problems, let me know and/or submit a merge request on the `avro/1.7.x` branch, and we'll work through it.

Thanks again!

**Pull request closed without merging**
